name: cd

on:
  push:
    branches:
      - main # specify the branch explicitly
  pull_request:

jobs:
  cd:
    runs-on: ubuntu-latest # specify the OS explicitly

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main # specify the branch explicitly

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.YOUR_GITHUB_TOKEN }} # use a personal access token instead of GITHUB_TOKEN
          publish_dir: ./dist
          publish_branch: gh-pages
          jekyll: false
          clean: true
